apiVersion: 2023-05-01
kind: ContainerApp
metadata:
  name: canvas-mcp-app
spec:
  configuration:
    ingress:
      external: true
      targetPort: 8000
      transport: http
    secrets:
      - name: canvas-url
        value: "https://uwwtw.instructure.com" # Set this when deploying
      - name: canvas-access-token
        value: "11830~2UYWcTf9Wy3xVDucc8L3nrYxGPCEBYn4XGQc2P4BFm4Pmuf2UR6MUDuC7vRwCYXH" # Set this when deploying
  template:
    containers:
      - name: canvas-mcp
        image: # Set this to your container registry image
        env:
          - name: CANVAS_URL
            secretRef: canvas-url
          - name: CANVAS_ACCESS_TOKEN
            secretRef: canvas-access-token
        resources:
          cpu: 0.5
          memory: 1Gi
    scale:
      minReplicas: 1
      maxReplicas: 1
